### ISSUE TITLE
Documentation site not reachable

### ISSUE THREAD

**Issue by nicostoehr** [glennklockwood/vpic-io#1]
Documentation site in README does not exist anymore, is there any mirror?

**Comment by glennklockwood** [comment]
I think this benchmark was rolled up into a suite of benchmarks which is maintained in a separate repository.  Maybe @sbyna can help.

**Comment by sbyna** [comment]
Yes, this benchmark along with many others are in https://github.com/hpc-io/h5bench.

**Comment by glennklockwood** [comment]
Thanks Suren!  I'll update this repo's description to point to h5bench and archive it.
